<template>
  <section class="assignment-console"><header><div><small>组织授权</small><h2>人员任职</h2></div><div class="user-picker"><el-input v-model="userId" placeholder="用户 ID" /><el-button @click="loadAssignments">载入任职</el-button></div></header>
    <section v-loading="reassignmentLoading" class="reassignment-panel" data-testid="reassignment-queue"><div class="panel-heading"><div><small>技术治理队列</small><h3>待改派审批任务</h3></div><el-tag effect="plain" type="danger">{{ reassignmentTasks.length }} 项待处理</el-tag></div><el-alert v-if="reassignmentError" :title="reassignmentError" type="error" :closable="false" show-icon /><div v-if="reassignmentTasks.length" class="reassignment-list"><article v-for="task in reassignmentTasks" :key="task.id" class="reassignment-card"><div class="queue-index">{{ String(task.id).padStart(3, '0') }}</div><div class="queue-detail"><strong>{{ task.target_title }}</strong><p>{{ task.node_name }} · {{ task.required_position_name }}</p><dl><div><dt>原处理人</dt><dd>{{ task.previous_assignee?.full_name || '已移除' }}</dd></div><div><dt>失效原因</dt><dd>{{ task.invalidation_reason }}</dd></div><div><dt>激活时间</dt><dd>{{ fmtTime(task.activated_at) }}</dd></div></dl></div><el-button type="primary" plain @click="openReassign(task)">改派</el-button></article></div><el-empty v-else-if="!reassignmentLoading && !reassignmentError" :image-size="48" description="当前没有待改派任务" /></section>
    <p class="notice">保存会完整替换该人员的任职集合；同一组织可保留多条不同岗位或任期的记录。</p>
    <article v-for="(assignment, index) in assignments" :key="assignment.client_ref" data-testid="assignment-row" :class="['assignment-row', { conflict: assignment.conflict }]"><div class="row-heading"><b>任职 {{ index + 1 }}</b><el-button text type="danger" @click="removeAssignment(index)">移除</el-button></div><div class="row-grid"><el-select v-model="assignment.organization_code" :disabled="Boolean(governanceTarget(assignment))" placeholder="组织"><el-option v-for="organization in organizations" :key="organization.code" :label="organization.name" :value="organization.code" /></el-select><el-select v-model="assignment.position_code" placeholder="岗位" @change="applyGovernanceTarget(assignment)"><el-option v-for="position in positions" :key="position.code" :label="position.name" :value="position.code" /></el-select><el-date-picker v-model="assignment.valid_from" value-format="YYYY-MM-DD" type="date" placeholder="生效日期" /><el-date-picker v-model="assignment.valid_until" value-format="YYYY-MM-DD" type="date" clearable placeholder="截止日期" /><el-select v-model="assignment.status"><el-option label="启用" value="active" /><el-option label="停用" value="inactive" /></el-select></div><div v-if="governanceTarget(assignment)" class="special-fields"><b>治理范围</b><el-tag type="warning">公司 / {{ governanceTarget(assignment) }}</el-tag></div><div v-if="positionFor(assignment)?.category === 'external'" class="special-fields"><b>外聘法律顾问</b><el-input v-model="assignment.provider_name" placeholder="服务单位" /><el-input v-model="assignment.service_scopes" placeholder="服务范围，以逗号分隔" /></div></article>
    <el-button data-testid="add-assignment" @click="addAssignment">添加任职</el-button><footer><el-input v-model="reason" maxlength="200" show-word-limit placeholder="变更原因（必填）" /><el-button type="primary" :disabled="!reason.trim() || !userId" @click="save">保存全部任职</el-button></footer>
    <ReassignTaskDialog v-model="reassignVisible" :task="selectedTask" @reassigned="loadReassignmentTasks" />
  </section>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as api from '@/api/organization'
import { listAwaitingReassignmentTasks } from '@/api/workflow'
import { useOrganizationStore } from '@/store/organization'
import ReassignTaskDialog from '@/components/workflow/ReassignTaskDialog.vue'

const route = useRoute(); const store = useOrganizationStore(); const userId = ref(String(route.query.user_id || '')); const reason = ref(''); const assignments = ref([])
const reassignmentTasks = ref([]); const reassignmentLoading = ref(false); const reassignmentError = ref(''); const selectedTask = ref(null); const reassignVisible = ref(false)
const positions = computed(() => store.positions || []); const organizations = computed(() => { const walk = nodes => nodes.flatMap(node => [node, ...walk(node.children || [])]); return walk(store.tree || []) })
const newClientRef = () => crypto.randomUUID?.() || `assignment-${Date.now()}-${Math.random()}`
const item = source => ({ client_ref: source?.client_ref || newClientRef(), id: source?.id, organization_code: source?.organization?.code || source?.organization_code || '', position_code: source?.position?.code || source?.position_code || '', valid_from: source?.valid_from || '', valid_until: source?.valid_until || null, status: source?.status || 'active', provider_name: source?.external?.provider_name || '', service_scopes: source?.external?.service_scopes?.join(', ') || '', conflict: false })
const positionFor = assignment => positions.value.find(position => position.code === assignment.position_code)
const governanceTarget = assignment => ({ 'governance.supply_leader': 'supplymanagement', 'governance.fund_leader': 'fundmanagement' })[assignment.position_code] || ''
function applyGovernanceTarget(assignment) { const target = governanceTarget(assignment); if (target) assignment.organization_code = target }
function addAssignment() { assignments.value.push(item()) }; function removeAssignment(index) { assignments.value.splice(index, 1) }; async function loadAssignments() { if (userId.value) assignments.value = (await api.getUserAssignments(userId.value)).map(item) }
const fmtTime = value => value ? String(value).replace('T', ' ').slice(0, 19) : '—'
async function loadReassignmentTasks() { reassignmentLoading.value = true; reassignmentError.value = ''; try { reassignmentTasks.value = await listAwaitingReassignmentTasks() } catch { reassignmentTasks.value = []; reassignmentError.value = '待改派任务加载失败' } finally { reassignmentLoading.value = false } }
function openReassign(task) { selectedTask.value = task; reassignVisible.value = true }
function validateExternal() { return assignments.value.every(assignment => assignment.position_code !== 'external.legal_counsel' || (assignment.valid_until && assignment.provider_name.trim() && assignment.service_scopes.trim() && assignment.service_scopes.split(',').every(scope => scope.trim()))) }
function assignmentPayload() { return { assignments: assignments.value.map(assignment => { const target = governanceTarget(assignment); if (target && assignment.organization_code !== target) throw new Error('治理岗位必须归属其指定子公司'); const position = positionFor(assignment); return { client_ref: assignment.client_ref, organization_code: assignment.organization_code, position_code: assignment.position_code, valid_from: assignment.valid_from, valid_until: assignment.valid_until || null, status: assignment.status, governance_scopes: target ? [{ scope_type: 'company', scope_ref: target }] : [], external: position?.category === 'external' ? { provider_name: assignment.provider_name.trim(), service_scopes: assignment.service_scopes.split(',').map(scope => scope.trim()).filter(Boolean) } : null } }) } }
function highlightConflicts(detail) { const refs = new Set((detail.conflicting_client_refs || []).map(String)); const ids = new Set((detail.assignment_ids || []).map(String)); assignments.value.forEach(assignment => { assignment.conflict = refs.has(String(assignment.client_ref)) || ids.has(String(assignment.id)) }) }
async function save() { if (!reason.value.trim() || !userId.value) return; if (!validateExternal()) return ElMessage.error('外聘法律顾问必须设置截止日期、服务单位和服务范围'); assignments.value.forEach(assignment => { assignment.conflict = false }); try { await ElMessageBox.confirm('保存将完整替换该人员的任职集合，确认继续？', '确认保存', { type: 'warning' }); assignments.value = (await api.replaceUserAssignments(userId.value, assignmentPayload(), reason.value.trim())).map(item); ElMessage.success('人员任职已保存') } catch (error) { const detail = error.response?.data?.detail; if (detail?.code === 'assignment_workflow_conflict') { highlightConflicts(detail); ElMessage.error(detail.message) } else if (error !== 'cancel' && error !== 'close') ElMessage.error(detail?.message || error.message || '人员任职保存失败') } }
onMounted(async () => { loadReassignmentTasks(); await Promise.all([store.loadTree(), store.loadPositions()]); if (userId.value) await loadAssignments() })
</script>

<style scoped>.assignment-console{padding:20px;min-height:100%;background:var(--app-bg)}header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}header small,.panel-heading small{color:var(--brand-vermilion);font-weight:700}h2{margin:2px 0;font-family:var(--font-display)}.user-picker{display:flex;gap:8px}.reassignment-panel{margin:18px 0 22px;padding:16px;background:var(--el-bg-color);border:1px solid var(--surface-border);border-top:3px solid var(--brand-vermilion)}.panel-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.panel-heading h3{margin:3px 0 0}.reassignment-list{display:grid;gap:10px;margin-top:14px}.reassignment-card{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:start;gap:12px;padding:13px;border:1px solid var(--el-border-color-lighter);background:var(--el-fill-color-extra-light)}.queue-index{color:var(--el-text-color-placeholder);font:600 12px/1.5 var(--el-font-family);letter-spacing:.08em}.queue-detail p{margin:4px 0;color:var(--el-text-color-secondary);font-size:13px}.queue-detail dl{display:flex;flex-wrap:wrap;gap:8px 20px;margin:9px 0 0}.queue-detail dl div{display:flex;gap:6px;font-size:12px}.queue-detail dt{color:var(--el-text-color-placeholder)}.queue-detail dd{margin:0;color:var(--el-text-color-regular)}.notice{margin:16px 0;color:var(--el-text-color-secondary)}.assignment-row{margin:12px 0;padding:14px;background:var(--el-bg-color);border:1px solid var(--surface-border);border-left:4px solid transparent}.assignment-row.conflict{border-color:var(--el-color-danger);border-left-color:var(--el-color-danger);background:var(--el-color-danger-light-9)}.row-heading{display:flex;justify-content:space-between;margin-bottom:10px}.row-grid{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:10px}.special-fields{display:flex;align-items:center;gap:10px;margin-top:10px}.special-fields .el-input{max-width:280px}footer{display:flex;gap:12px;margin-top:20px;align-items:center}footer .el-input{max-width:540px}@media(max-width:900px){.row-grid{grid-template-columns:1fr 1fr}.reassignment-card{grid-template-columns:32px 1fr}.reassignment-card>.el-button{grid-column:2}.special-fields,footer{align-items:stretch;flex-direction:column}.special-fields .el-input,footer .el-input{max-width:none}}</style>
