import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import PositionsView from './positions.vue'

const { api, store } = vi.hoisted(() => ({ api: { createPosition: vi.fn(), updatePosition: vi.fn(), replacePositionPermissions: vi.fn() }, store: { positions: [{ id: 7, code: 'supply.business_handler', name: '业务经办', category: 'business', is_active: true, permissions: [{ permission_code: 'supply.contract.view', data_scope: 'company', scope_ref: 'supplymanagement' }] }], permissions: [{ code: 'supply.contract.view', name: '查看合同', resource: 'supply.contract' }, { code: 'supply.portal.enter', name: '供应链门户', resource: 'supply.portal' }], tree: [{ code: 'supplymanagement', name: '供应链公司', organization_type: 'company', is_active: true, children: [] }], loadPositions: vi.fn(), loadPermissions: vi.fn(), loadTree: vi.fn() } }))
vi.mock('@/api/organization', () => api)
vi.mock('@/store/organization', () => ({ useOrganizationStore: () => store }))
vi.mock('element-plus', async importOriginal => ({ ...await importOriginal(), ElMessage: { success: vi.fn(), error: vi.fn() }, ElMessageBox: { confirm: vi.fn() } }))
const stubs = { ElTable: { props: ['data'], template: '<div><slot :row="data[0]" /></div>' }, ElTableColumn: true, ElButton: { emits: ['click'], template: '<button @click="$emit(\'click\')"><slot /></button>' }, ElInput: true, ElSelect: true, ElOption: true, ElOptionGroup: true, ElForm: true, ElFormItem: true, ElSwitch: true, ElTag: true, ElDrawer: { template: '<div><slot /></div>' } }

describe('PositionsView', () => {
  beforeEach(() => { vi.clearAllMocks(); store.loadPositions.mockResolvedValue(); store.loadPermissions.mockResolvedValue(); store.loadTree.mockResolvedValue(); api.updatePosition.mockResolvedValue({ id: 7 }); api.replacePositionPermissions.mockResolvedValue([]) })
  it('shows saved permission counts without a user selector', async () => { const wrapper = mount(PositionsView, { global: { stubs } }); await flushPromises(); expect(wrapper.text()).toContain('已配置 1 项权限'); expect(wrapper.find('[data-testid="user-permission-selector"]').exists()).toBe(false) })
  it('saves metadata without replacing permissions', async () => { const wrapper = mount(PositionsView, { global: { stubs } }); await flushPromises(); wrapper.vm.reason = '岗位信息调整'; await wrapper.vm.saveMetadata(); expect(api.updatePosition).toHaveBeenCalledWith(7, expect.objectContaining({ code: 'supply.business_handler' }), '岗位信息调整'); expect(api.replacePositionPermissions).not.toHaveBeenCalled() })
  it('reports permission failure without claiming metadata success', async () => { const { ElMessage, ElMessageBox } = await import('element-plus'); ElMessageBox.confirm.mockResolvedValue(); api.replacePositionPermissions.mockRejectedValue({ response: { data: { detail: { message: 'scope invalid' } } } }); const wrapper = mount(PositionsView, { global: { stubs } }); await flushPromises(); wrapper.vm.reason = '模板调整'; await wrapper.vm.savePermissions(); expect(ElMessage.success).not.toHaveBeenCalledWith('岗位信息已保存'); expect(ElMessage.error).toHaveBeenCalledWith('scope invalid') })
  it('normalizes portal and own scopes before sending a template', async () => { const { ElMessageBox } = await import('element-plus'); ElMessageBox.confirm.mockResolvedValue(); const wrapper = mount(PositionsView, { global: { stubs } }); await flushPromises(); wrapper.vm.reason = '模板调整'; wrapper.vm.form.permissions = [{ permission_code: 'supply.portal.enter', data_scope: 'platform', scope_ref: '' }, { permission_code: 'supply.contract.view', data_scope: 'own', scope_ref: 'bad' }]; wrapper.vm.normalizeScope(wrapper.vm.form.permissions[0]); wrapper.vm.normalizeScope(wrapper.vm.form.permissions[1]); await wrapper.vm.savePermissions(); expect(api.replacePositionPermissions).toHaveBeenCalledWith(7, [{ permission_code: 'supply.portal.enter', data_scope: 'platform', scope_ref: 'supplymanagement' }, { permission_code: 'supply.contract.view', data_scope: 'own', scope_ref: '' }], '模板调整') })
})
